"""init jobs schema

Revision ID: 26877f091945
Revises: 
Create Date: 2026-04-29 20:34:21.878916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '26877f091945'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('jobs', sa.Column('language', sa.String(length=20), nullable=True))
    op.add_column('jobs', sa.Column('seniority', sa.String(length=50), nullable=True))
    op.add_column('jobs', sa.Column('remote_type', sa.String(length=50), nullable=True))
    op.add_column('jobs', sa.Column('employment_type', sa.String(length=50), nullable=True))
    op.add_column('jobs', sa.Column('status', sa.String(length=50), server_default='new', nullable=False))
    op.add_column('jobs', sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('jobs', sa.Column('skills_source', sa.String(length=50), server_default='manual', nullable=False))
    op.add_column('jobs', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('jobs_raw', sa.Column('processing_status', sa.String(length=50), server_default='raw', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs_raw', 'processing_status')
    op.drop_column('jobs', 'updated_at')
    op.drop_column('jobs', 'notes')
    op.drop_column('jobs', 'description')
    op.drop_column('jobs', 'skills_source')
    op.drop_column('jobs', 'skills')
    op.drop_column('jobs', 'status')
    op.drop_column('jobs', 'employment_type')
    op.drop_column('jobs', 'remote_type')
    op.drop_column('jobs', 'seniority')
    op.drop_column('jobs', 'language')
    op.drop_column('jobs', 'location')
    # ### end Alembic commands ###
