RAW_JOB_STATUS_RAW = "raw"
RAW_JOB_STATUS_REVIEWED = "reviewed"
RAW_JOB_STATUS_AI_DRAFTED = "ai_drafted"
RAW_JOB_STATUS_STRUCTURED = "structured"

RAW_JOB_PROCESSING_STATUSES = {
    RAW_JOB_STATUS_RAW,
    RAW_JOB_STATUS_REVIEWED,
    RAW_JOB_STATUS_AI_DRAFTED,
    RAW_JOB_STATUS_STRUCTURED,
}


JOB_DRAFT_STATUS_DRAFT = "draft"
JOB_DRAFT_STATUS_FAILED = "failed"
JOB_DRAFT_STATUS_REVIEWED = "reviewed"
JOB_DRAFT_STATUS_SAVED = "saved"
JOB_DRAFT_STATUS_ACCEPTED = "accepted"

JOB_DRAFT_STATUSES = {
    JOB_DRAFT_STATUS_DRAFT,
    JOB_DRAFT_STATUS_FAILED,
    JOB_DRAFT_STATUS_REVIEWED,
    JOB_DRAFT_STATUS_SAVED,
    JOB_DRAFT_STATUS_ACCEPTED,
}
